### ISSUE TITLE
ref window doesn't work with perldoc after recent change

### ISSUE THREAD

**Issue by y** [thinca/vim-ref#53]
This change here has broken ref for me:
https://github.com/thinca/vim-ref/commit/5a25164eca2f71804b5081bf5a0b7466cf822e0c#diff-41bcadaad03c91619bb7496381524a94L50

Before the change (and now after reverting that changed line) 'K' would open perldoc in a new window, after the change vim goes back to its default behavior of looking for a manpage , even though `map K` is still mapping to `<Plug>(ref-keyword)`. I don't have any custom ref settings.

**Comment by thinca** [comment]
Thanks for bug report :smiley:   I fixed. 7d019e8fe3e27dad9d1f49d7e43348b4b7992382
Please check.
